#!/usr/bin/php
<?php
$html_title="OWINFS Declaración de unidad política";
include 'include/head_etc.php'
?>
    <div id="main">
<?php
$sidebar_title="Acerca de OWINFS";
include 'include/sidebar_about_es.php';
include 'include/navbar.php';
?>

      <div id="content" class="singlecolumn">
        <a href="statement-political-unity">English</a>
        &nbsp;
        Español
        &nbsp;
        <a href="declaration-d-unite">Français</a>
        &nbsp;
        <a href="documento-di-unita">Italiano</a>
        <div id="content-header">
          <h1 class="title" align="center">Declaración de unidad política de la Red</h1>
          <h1 class="title" align="center">‘NUESTRO MUNDO NO ESTÁ EN VENTA’</h1>
        </div> <!-- /#content-header -->
        <p>&nbsp;</p>
        <div id="content-area">
<p align="center"><strong>FRENEMOS LA GLOBALIZACI&Oacute;N DE LAS TRANSNACIONALES:</strong><strong><br /> OTRO MUNDO ES POSIBLE</strong></p>
<p align="center"><strong>Declaraci&oacute;n de unidad pol&iacute;tica de la Red<br /> &lsquo;NUESTRO MUNDO NO EST&Aacute; EN VENTA&rsquo;</strong></p>
<p><strong>Introducci&oacute;n: nuestro desaf&iacute;o</strong></p>
<p>&lsquo;Nuestro Mundo No Est&aacute; en Venta&rsquo; es una red mundial de organizaciones, activistas y movimientos sociales abocados a combatir los acuerdos de comercio e inversiones que promueven la globalizaci&oacute;n orientada por las transnacionales y benefician a las empresas m&aacute;s poderosas del mundo a costa de los pueblos y el medio ambiente.</p>
<p>Contra ese proceso de globalizaci&oacute;n orientada por las transnacionales, sostenemos la visi&oacute;n de una econom&iacute;a mundial fundada en principios de justicia econ&oacute;mica, sustentabilidad ecol&oacute;gica y responsabilidad democr&aacute;tica &ndash;una econom&iacute;a que privilegie los intereses de los pueblos y las personas antes que los de las empresas. Una econom&iacute;a erigida en torno a los intereses de los verdaderos productores y consumidores &ndash;trabajadores, campesinos, agricultores familiares, pescadores artesanales, peque&ntilde;os y medianos&nbsp; productores&mdash;y las necesidades de quienes se encuentran marginados por el sistema imperante, como es el caso de las mujeres y los pueblos ind&iacute;genas.</p>
<p>Creemos que un sistema justo debe proteger y no socavar la diversidad cultural, biol&oacute;gica, econ&oacute;mica y social; priorizar la econom&iacute;a y el comercio local; salvaguardar los derechos ambientales, culturales, sociales y laborales reconocidos internacionalmente; restituir la soberan&iacute;a y autodeterminaci&oacute;n de los pueblos, y proteger los procesos democr&aacute;ticos de toma decisiones a escala nacional y subnacional.</p>
<p>A diferencia del conjunto de valores, prioridades y pol&iacute;ticas del mismo talle para todos impuesto por organismos internacionales como la Organizaci&oacute;n Mundial del Comercio (OMC) y procesos internacionales de soluci&oacute;n de controversias comerciales que no son responsables ante nadie, la democracia no es tan s&oacute;lo la realizaci&oacute;n de elecciones, sino un sistema de gobierno en el que el pueblo tiene el control de los asuntos que afectan directamente la vida de la gente. Democracia significa no estar sujeto a mecanismos de decisi&oacute;n velados, carentes de transparencia y que no le rinden cuentas a nadie, tales como los procesos de soluci&oacute;n de controversias de la OMC. La democracia implica que el pueblo asuma el control de las fuerzas que afectan directamente la vida de la gente.</p>
<p>Desde su creaci&oacute;n en 1995, la OMC ha sido promocionada como una instituci&oacute;n que traer&iacute;a mayor prosperidad, aumentar&iacute;a el empleo, reducir&iacute;a la pobreza, disminuir&iacute;a las desigualdades y fomentar&iacute;a el desarrollo sustentable en todo el mundo mediante la aplicaci&oacute;n de m&aacute;s &ldquo;libre comercio&rdquo;. Diez a&ntilde;os despu&eacute;s es innegable que la OMC ha tenido efectos exactamente opuestos.</p>
<p>El r&eacute;gimen de intercambio comercial administrado por la OMC ha demostrado ser profundamente hostil a cualquier tipo de medida orientada a fomentar el desarrollo, aliviar la pobreza y contribuir a asegurar la supervivencia humana y ecol&oacute;gica a escala local y mundial. Amparadas tras el disfraz del &ldquo;libre comercio&rdquo;, las reglas de la OMC son utilizadas para forzar la apertura de nuevos mercados y para librarlos al control de las empresas transnacionales.</p>
<p>Al mismo tiempo, las grandes potencias comerciales han intentado utilizar la OMC para promover y consolidar en manos de empresas transnacionales el control de las actividades econ&oacute;micas y sociales en esferas que trascienden el comercio, tales como el desarrollo, las inversiones, la pol&iacute;tica de competencia, la prestaci&oacute;n de servicios sociales, la protecci&oacute;n del medioambiente y la contrataci&oacute;n p&uacute;blica o compras del Estado.</p>
<p>La liberalizaci&oacute;n a gran escala en estas esferas obligar&aacute; a los pa&iacute;ses en desarrollo a renunciar a muchos de los instrumentos de desarrollo econ&oacute;mico que fueron utilizados por los pa&iacute;ses industrializados para fortalecer sus econom&iacute;as y generar empleo. Es m&aacute;s, las disposiciones vigentes en la OMC &ndash;as&iacute; como las que se est&aacute;n negociando actualmente en su seno&mdash;pueden efectivamente &lsquo;perpetuar&rsquo; los programas de &ldquo;ajuste estructural&rdquo; del Banco Mundial y el Fondo Monetario Internacional torn&aacute;ndolos irreversibles.</p>
<p>De otra parte, los mecanismos de gobierno y toma de decisiones utilizados en la OMC son c&eacute;lebres por su recurso a las amenazas, el enga&ntilde;o y la manipulaci&oacute;n, y por su falta de transparencia y el car&aacute;cter excluyente y antidemocr&aacute;tico de sus procesos.</p>
<p>Los efectos destructivos sociales, pol&iacute;ticos y ambientales del modelo neoliberal de globalizaci&oacute;n pro-empresarial son los que han despertado resistencia creciente entre un espectro amplio de organizaciones de la sociedad civil y movimientos sociales de todo el mundo, incluso durante las Cumbres de la OMC en Seattle, Doha, Canc&uacute;n y&nbsp; Hong Kong.</p>
<p>Nuestro Mundo No Est&aacute; en Venta forma parte de ese movimiento mundial de resistencia.</p>
<p>Diez a&ntilde;os despu&eacute;s de su creaci&oacute;n, ha quedado en evidencia que la posibilidad de conseguir que la OMC se encamine en direcci&oacute;n a un programa de reformas positivas es m&iacute;nima, si no nula. Es absolutamente necesario cambiar. El sistema imperante hoy en d&iacute;a es tal que:</p>
<ul>
<li>se est&aacute;n perdiendo empleos y medios de vida, los derechos humanos est&aacute;n amenazados, se ha saqueado el medioambiente y los sistemas democr&aacute;ticos est&aacute;n debilitados;</li>
</ul>
<ul>
<li>se est&aacute; socavando a las econom&iacute;as locales y nacionales; y los trabajadores, campesinos, agricultores familiares, consumidores, mujeres y pueblos ind&iacute;genas son quienes resultan m&aacute;s desfavorecidos y explotados;</li>
</ul>
<ul>
<li>a los gobiernos se les est&aacute; restando capacidad &ndash;y a veces incluso se les est&aacute; privando de ella&mdash;para garantizar el acceso a los medios esenciales de vida, para promover la salud, la seguridad y la soberan&iacute;a alimentaria y para proteger la diversidad cultural y biol&oacute;gica.</li>
</ul>
<p>Los resultados negativos del sistema econ&oacute;mico mundial imperante est&aacute;n dando impulso a movimientos democr&aacute;ticos en todo el mundo que reclaman cambios a trav&eacute;s de las urnas y la movilizaci&oacute;n callejera. Las autoridades electas de muchos pa&iacute;ses han perdido la fe en el sistema actual de gobernanza econ&oacute;mica mundial. Cada vez con mayor frecuencia, algunos de los economistas y tecn&oacute;cratas que crearon y respaldaron este sistema est&aacute;n empezando a cuestionarlo, ya que los resultados han demostrado ser casi antag&oacute;nicos a lo prometido. Todo esto ocurre en un contexto de desigualdad creciente &ndash;tanto entre las naciones como dentro de cada pa&iacute;s&mdash;y de resurgimiento del militarismo.</p>
<p>Tenemos que oponer resistencia y rechazar las pretensiones de la OMC de liberalizaci&oacute;n forzosa del comercio mundial seg&uacute;n modalidades nocivas para la justicia econ&oacute;mica, el bienestar social, la equidad de g&eacute;nero y la sustentabilidad ecol&oacute;gica. Es imperativo restringir el poder y la autoridad de la OMC y hacerla retroceder de muchas esferas en las que se ha impuesto forzosamente como en la agricultura, los servicios y los derechos de propiedad intelectual.</p>
<p>Al mismo tiempo, para evitar el panorama cada vez m&aacute;s recurrente de cat&aacute;strofe social y ecol&oacute;gica, tenemos que crear nuevas instituciones para facilitar el comercio, la producci&oacute;n y la distribuci&oacute;n para el bien com&uacute;n.</p>
<p>Necesitamos reemplazar el r&eacute;gimen actual de comercio &ndash;del que forman parte tanto la OMC como otros acuerdos regionales y tratados bilaterales de comercio e inversiones&mdash;con un nuevo sistema de comercio socialmente justo y ecol&oacute;gicamente sustentable para el siglo XXI.</p>
<p><strong>Nuestras metas</strong></p>
<p>Desde 1998, los miembros de la red Nuestro Mundo No Est&aacute; en Venta han cooperado entre s&iacute; compartiendo an&aacute;lisis, dise&ntilde;ando estrategias y coordinando acciones a escala internacional con el fin de fomentar el desarrollo de econom&iacute;as alternativas, justas y sustentables.</p>
<p>Dedicamos nuestros esfuerzos al desarrollo de un nuevo sistema de comercio sometido al control democr&aacute;tico, que contribuya al avance de la justicia econ&oacute;mica, el bienestar social, la equidad de g&eacute;nero y la sustentabilidad ecol&oacute;gica, y que provea empleo digno y los bienes y servicios necesarios para todas las personas.</p>
<p>Apoyamos el desarrollo de econom&iacute;as locales vibrantes y los derechos de los trabajadores, campesinos, migrantes, agricultores familiares, consumidores, mujeres y pueblos ind&iacute;genas. Consideramos que la autodeterminaci&oacute;n de los pueblos no debe estar subordinada a compromisos comerciales internacionales. Entre otras cosas, eso requiere que los procesos y mecanismos de decisi&oacute;n y ejecuci&oacute;n a todos los niveles de gobierno sean democr&aacute;ticos, transparentes e incluyentes.</p>
<p>Reconocemos que un sistema de comercio internacional socialmente justo tiene que darle prioridad a los derechos y bienestar de los trabajadores, campesinos, migrantes y agricultores familiares que producen nuestros bienes, servicios y alimentos.</p>
<p>Exigimos que los gobiernos y las agencias internacionales cesen su embestida contra los derechos fundamentales de los trabajadores, que desistan de anular las conquistas logradas por la lucha de los trabajadores, que frenen el debilitamiento de la seguridad laboral y la nivelaci&oacute;n hacia abajo de los salarios, y reclamamos que fortalezcan los derechos de los trabajadores en todo el mundo.</p>
<p>Nos oponemos a los acuerdos y negociaciones de liberalizaci&oacute;n comercial que privan a las comunidades ind&iacute;genas y locales del acceso a los recursos naturales de los que dependen para su supervivencia, garantiz&aacute;ndoselo en cambio a las empresas.</p>
<p>Es tambi&eacute;n imprescindible que se respeten, fomenten y ejerzan otros derechos humanos fundamentales, empezando por la autodeterminaci&oacute;n de los pueblos ind&iacute;genas y la dotaci&oacute;n p&uacute;blica y acceso universal a servicios sociales b&aacute;sicos como la educaci&oacute;n, la salud, el agua potable para uso humano y la seguridad y soberan&iacute;a alimentaria.</p>
<p>La integridad ecol&oacute;gica tiene que ser asimismo una meta de un sistema mundial de comercio transformado. Eso implica, entre otras cosas, que se tiene que regular el comercio y las inversiones de manera tal que se revierta el recalentamiento de la Tierra; los acuerdos multilaterales sobre medioambiente tienen que gozar de primac&iacute;a frente a los acuerdos comerciales; no se puede permitir que los acuerdos comerciales arrastren y nivelen hacia abajo las normas ambientales; el derecho de las personas y los pueblos a rechazar los organismos gen&eacute;ticamente modificados tiene que respetarse, al igual que el derecho a preservar las semillas diversas de los agricultores y los bosques primarios, y promover el bienestar animal.</p>
<p><strong>Qu&eacute; nos proponemos</strong></p>
<p><strong>Apuntalar el derecho de elecci&oacute;n de los pueblos: autodeterminaci&oacute;n, democracia y desarrollo</strong></p>
<p><em>Reafirmamos el derecho fundamental de todos los pa&iacute;ses a ejecutar pol&iacute;ticas econ&oacute;micas y productivas que fortalezcan el desarrollo econ&oacute;mico genuino, generen empleos dignos y protejan los medios de vida y vigoricen el medioambiente. Todos los pa&iacute;ses, y particularmente los m&aacute;s empobrecidos, tienen que gozar del derecho a optar por la aplicaci&oacute;n de pol&iacute;ticas (tales como las disposiciones relativas al &lsquo;contenido nacional&rsquo;) que apunten a incrementar la capacidad de sus propios sectores productivos, especialmente las peque&ntilde;as y medianas empresas. Los pa&iacute;ses deben asimismo conservar la capacidad (o espacio pol&iacute;tico) para modelar estrategias econ&oacute;micas y ambientales de desarrollo al servicio de los sectores m&aacute;s vulnerables de su poblaci&oacute;n. El envi&oacute;n en pos de la &ldquo;coherencia&rdquo; entre las instituciones internacionales se ha convertido en un medio para denegar ese espacio pol&iacute;tico: el Fondo Monetario Internacional, el Banco Mundial y algunos pa&iacute;ses donantes obligan a los gobiernos a aplicar pol&iacute;ticas neoliberales mientras que la OMC y otros acuerdos de comercio e inversiones las perpet&uacute;an torn&aacute;ndolas irreversibles.</em>Por ello:</p>
<ul type="disc">
<li>Nuestro Mundo No Est&aacute; en Venta exige el fin de las pr&aacute;cticas secretas y coercitivas que se han transformado en el sello distintivo de las negociaciones comerciales, especialmente en la OMC, donde un pu&ntilde;ado de gobiernos poderosos &ndash;actuando a menudo en nombre de sus elites empresariales&mdash;coaccionan a otros gobiernos m&aacute;s d&eacute;biles para alcanzar sus objetivos.</li>
</ul>
<ul type="disc">
<li>Hay que impedir que los aranceles aduaneros y otras medidas comerciales sean desmantelados, dejando las econom&iacute;as locales y nacionales &ndash;en particular aquellas de los pa&iacute;ses m&aacute;s empobrecidos y/o los sectores econ&oacute;micos m&aacute;s d&eacute;biles&mdash;libradas a la merced de las empresas transnacionales y poniendo en riesgo el desarrollo econ&oacute;mico local y nacional, las leyes y normas laborales, el medioambiente y la salud p&uacute;blica y de los consumidores.</li>
</ul>
<ul type="disc">
<li>No podemos permitir que las negociaciones de &ldquo;libre comercio&rdquo; en la OMC y otras instancias contin&uacute;en funcionando cual caballo de Troya para garantizarle reglas favorables a las empresas en materia de inversiones, pol&iacute;tica de competencia, contrataci&oacute;n p&uacute;blica y compras del Estado, acceso al mercado, producci&oacute;n agropecuaria, reglamentaci&oacute;n nacional de los servicios y derechos de propiedad intelectual. Tampoco se puede permitir que siga rigiendo la din&aacute;mica actual de fuerzas seg&uacute;n la cual los pa&iacute;ses ricos industrializados le imponen su agenda econ&oacute;mica de prioridades a los pa&iacute;ses m&aacute;s empobrecidos.</li>
</ul>
<ul type="disc">
<li>Hay que impedir que los ajustes estructurales y las condicionalidades de la deuda sigan us&aacute;ndose para imponerle la liberalizaci&oacute;n del comercio a los pa&iacute;ses del tercer mundo y otros. Es imprescindible que el Fondo Monetario Internacional, el Banco Mundial y los bancos regionales de desarrollo anulen todas las deudas que a&uacute;n mantienen con ellos los pa&iacute;ses en desarrollo y en transici&oacute;n, de manera tal que estos puedan reasignar esos fondos a la satisfacci&oacute;n de las necesidades apremiantes de su poblaci&oacute;n.</li>
</ul>
<p><strong>Garantizar la primac&iacute;a de los derechos sociales y el medioambiente</strong></p>
<p><em>Sostenemos que proteger y extender los derechos sociales, satisfacer las necesidades b&aacute;sicas y proteger nuestro medioambiente es esencial para la vida. Es inadmisible que las reglas de la OMC y de otros acuerdos de &lsquo;comercio&rsquo; los socaven.</em>Por ello:</p>
<ul type="disc">
<li>Ning&uacute;n acuerdo comercial o de inversiones debe socavar o tener primac&iacute;a sobre los acuerdos internacionales que promueven la justicia social, econ&oacute;mica y ambiental, entre ellos, mas no exclusivamente:  
<ul type="circle">
<li>la Declaraci&oacute;n de la Organizaci&oacute;n Internacional del Trabajo (OIT) relativa a los Principios y Derechos Fundamentales en el trabajo (que abarca los cuatro derechos laborales fundamentales);</li>
<li>el Convenio sobre la Diversidad Biol&oacute;gica y su Protocolo de Bioseguridad y otros acuerdos multilaterales sobre el medioambiente;</li>
<li>la Declaraci&oacute;n Universal de los Derechos Humanos y los convenios a ella asociados en el marco de la Organizaci&oacute;n de las Naciones Unidas (ONU): el Pacto Internacional de Derechos Econ&oacute;micos, Sociales y culturales; y el Pacto Internacional de Derechos Civiles y Pol&iacute;ticos;</li>
<li>el proyecto de Declaraci&oacute;n de las Naciones Unidas sobre los Derechos de las Poblaciones Ind&iacute;genas;</li>
<li>la Convenci&oacute;n sobre la Eliminaci&oacute;n de todas las Formas de Discriminaci&oacute;n Contra la Mujer; y</li>
<li>la Convenci&oacute;n Internacional sobre la Protecci&oacute;n de los Derechos de todos los Trabajadores Migratorios y de sus Familiares.</li>
</ul>
</li>
</ul>
<ul type="disc">
<li>Los gobiernos deben conservar el derecho soberano a determinar c&oacute;mo regulan sus servicios de manera tal que se satisfagan las necesidades de su poblaci&oacute;n, su econom&iacute;a y sociedad y que se honren sus dem&aacute;s obligaciones internacionales y constitucionales, entre ellas aquellas de cara a las mujeres, los pueblos ind&iacute;genas, los j&oacute;venes y ni&ntilde;os, los adultos mayores y los pobres.</li>
</ul>
<ul type="disc">
<li>El derecho de los gobiernos a aplicar el principio de precauci&oacute;n con el fin de proteger la salud p&uacute;blica, el medioambiente y la agricultura frente a riesgos desconocidos tiene que primar sobre cualquier acuerdo o disposici&oacute;n comercial.</li>
</ul>
<ul type="disc">
<li>Es imperativo evitar cualquier recorte arancelario que perjudique al medioambiente y el desarrollo sustentable como resultado del crecimiento inadecuado del comercio de recursos naturales y otros bienes sensibles desde el punto de vista ambiental.</li>
</ul>
<ul type="disc">
<li>Hay que frenar el debilitamiento de la ONU a manos de las pro-empresariales instituciones de Bretton Woods (Banco Mundial y FMI), la OMC y las grandes potencias, y fortalecer el sistema de acuerdos y agencias de Naciones Unidas.</li>
</ul>
<p><strong>Proteger los servicios esenciales</strong></p>
<p><em>Adherimos al principio fundamental de que ning&uacute;n acuerdo comercial o de inversiones debe vulnerar el derecho soberano de los gobiernos a garantizar el acceso de la poblaci&oacute;n a los bienes esenciales para la vida, y a promover la salud y bienestar de sus pueblos&nbsp; y proteger el medioambiente.</em>Por ello:</p>
<ul type="disc">
<li>No se debe presionar a los pa&iacute;ses a aceptar reglas de comercio que coarten el ejercicio de esa soberan&iacute;a, ya sea a trav&eacute;s de la OMC y su Acuerdo General sobre el Comercio de Servicios (AGCS o GATS, por su sigla en ingl&eacute;s) o a trav&eacute;s de otros acuerdos regionales o bilaterales.&nbsp;</li>
</ul>
<ul type="disc">
<li>Es imprescindible excluir expl&iacute;citamente de todos los acuerdos de comercio e inversiones a&nbsp; todos aquellos sectores directamente asociados a dichos servicios esenciales, entre ellos los de salud, educaci&oacute;n, cultura audiovisual, asistencia social, agua potable y energ&iacute;a.</li>
</ul>
<ul type="disc">
<li>Las reglas relativas a la reglamentaci&oacute;n nacional, los subsidios y la contrataci&oacute;n p&uacute;blica de servicios obstaculizan por su propia naturaleza el ejercicio de ese derecho soberano, y no se las deber&iacute;a incluir en los acuerdos de comercio e inversiones.</li>
</ul>
<p><em>Hoy en d&iacute;a se est&aacute; ejerciendo much&iacute;sima presi&oacute;n sobre los pa&iacute;ses para que sometan sus servicios esenciales a las reglas del AGCS cuyo efecto es promover las privatizaciones. Por otra parte, cuando un pa&iacute;s que es o ha sido v&iacute;ctima de la desregulaci&oacute;n y privatizaci&oacute;n de sus servicios esenciales en cumplimiento de las exigencias de &ldquo;ajuste estructural&rdquo;, asume compromisos con arreglo a las reglas del AGCS, dichas reglas sirven para perpetuar esas privatizaciones torn&aacute;ndolas irreversibles. El AGCS fomenta de ese modo la apertura de los mercados nacionales y el ingreso de empresas transnacionales, y promueve as&iacute; el avance del modelo econ&oacute;mico neoliberal.</em>Por ello:</p>
<ul type="disc">
<li>Es imperativo retraer esas exigencias de ajuste estructural, no perpetuarlas, y hay que impedir que los nuevos pr&eacute;stamos o donaciones a los pa&iacute;ses sean condicionados al cumplimiento de dichas exigencias, del mismo modo que hay que objetar que se presione a los pa&iacute;ses para que sometan sus servicios esenciales a las reglas del AGCS.</li>
</ul>
<p><strong>Defender el conocimiento, la cultura y las formas de vida como esencia de la civilizaci&oacute;n</strong></p>
<p><em>Consideramos el conocimiento, la cultura y la educaci&oacute;n como fuerzas motrices de la civilizaci&oacute;n que no pueden ser reducidas a meras mercanc&iacute;as comerciables o propiedad privada.</em></p>
<p><em>No existe ning&uacute;n fundamento leg&iacute;timo para la inclusi&oacute;n de reclamos de propiedad intelectual en un acuerdo de comercio. M&aacute;s a&uacute;n, todos los pa&iacute;ses tienen la responsabilidad y la obligaci&oacute;n de proteger la salud p&uacute;blica y el bienestar de sus ciudadanos. Las reglas de propiedad intelectual vigentes en los acuerdos comerciales, tales como el acuerdo de la OMC sobre los Aspectos de los Derechos de Propiedad Intelectual relacionados con el Comercio ( ADPIC), obstruyen el acceso de los pueblos a medicamentos vitales, semillas y otros bienes esenciales, conducen a la destrucci&oacute;n de la biodiversidad y la apropiaci&oacute;n privada de los seres vivos y el conocimiento tradicional. Adem&aacute;s le impiden a los pa&iacute;ses empobrecidos elevar sus niveles de bienestar econ&oacute;mico y social y defender su singularidad identitaria y su patrimonio.</em>Por ello:</p>
<ul>
<li>Los gobiernos deben conservar el derecho irrestricto a limitar los derechos de propiedad que confieren las patentes, a fin de proteger el inter&eacute;s p&uacute;blico y el bien com&uacute;n en esas esferas, especialmente con relaci&oacute;n a los medicamentos, las semillas y los seres vivos y sus partes.</li>
</ul>
<ul>
<li>El patentamiento&nbsp; de formas de vida, incluso microorganismos, tiene que prohibirse en todas las legislaciones nacionales e internacionales.</li>
</ul>
<ul>
<li>Tenemos que defender la diversidad cultural genuina contra el impacto homogenizador de los mercados mundiales y los monopolios del conocimiento, la tecnolog&iacute;a y las telecomunicaciones.</li>
</ul>
<p><strong>Preservar y extender la seguridad y soberan&iacute;a alimentaria</strong></p>
<p><em>Sostenemos que el derecho a la alimentaci&oacute;n es un derecho humano fundamental. El Acuerdo Agr&iacute;cola de la OMC subordina este derecho al lucro empresarial. La OMC fomenta un sistema alimentario fundado en una agricultura industrializada de exportaci&oacute;n e intensiva en inversi&oacute;n de capital, que est&aacute; profundizando la concentraci&oacute;n empresarial a lo largo de toda la cadena alimentaria a la vez que socava el sustento, los derechos, la salud y las condiciones de vida y laborales de los trabajadores agr&iacute;colas y de la alimentaci&oacute;n, minando as&iacute; a&uacute;n m&aacute;s la seguridad alimentaria.</em></p>
<p><em>Adem&aacute;s no admite ni reconoce que la agricultura es un modo de vida y un cimiento importante de la comunidad y la cultura. En consecuencia, sus pol&iacute;ticas y aquellas de otros acuerdos comerciales alientan una concentraci&oacute;n mayor y acrecientan el poder de las empresas transnacionales y provocan la expulsi&oacute;n de millones de campesinos, agricultores familiares y trabajadores agr&iacute;colas que son despojados de sus tierras y excluidos de la producci&oacute;n en los pa&iacute;ses del Norte y del Sur. Desde que se iniciaron los programas de &ldquo;ajuste estructural&rdquo; y se cre&oacute; la OMC, muchos campesinos, agricultores familiares y trabajadores agr&iacute;colas han sido desplazados de la tierra y sufrido hambre, empujando a muchos de ellos al suicidio debido a la liberalizaci&oacute;n de la agricultura mediante recortes arancelarios, la abolici&oacute;n de las restricciones cuantitativas y la aplicaci&oacute;n de pol&iacute;ticas nacionales agropecuarias inequitativas. Al mismo tiempo, muchos subsidios que benefician al agronegocio &ndash;incluso a la agricultura industrial de exportaci&oacute;n&mdash;se&nbsp; han incrementado en lugar que recortado.</em></p>
<p><em>Por otra parte, mientras estas reglas le permiten a las empresas comercializadoras crecientemente poderosas presionar hacia abajo los precios que se le paga a los agricultores de todo el mundo por sus productos, la concentraci&oacute;n de la distribuci&oacute;n y procesamiento de alimentos alentada por las reglas de la OMC para la agricultura y los servicios han llevado a un aumento de los precios al consumidor.&nbsp;</em>Por ello:</p>
<ul>
<li>
<p>Para evitar una escalada mayor de hambre, desplazados y muertes, es imperativo que se emprendan acciones inmediatamente para restringir las pol&iacute;ticas agr&iacute;colas, de comercio e inversiones que estimulan la superproducci&oacute;n cr&oacute;nica, y prohibir el<em>dumping</em>de productos agr&iacute;colas en los mercados mundiales a precios por debajo del costo de producci&oacute;n, practicado por las grandes empresas transnacionales agroalimentarias y otros agentes que intervienen en el comercio mundial agropecuario. Hay que prohibir los subsidios directos e indirectos a las exportaciones que conducen al<em>dumping</em>. Los pa&iacute;ses deben conservar y&nbsp; reafirmar su derecho soberano a proteger sus mercados y sectores agr&iacute;colas contra el<em>dumping</em>, y poder as&iacute; aplicar medidas que activa y efectivamente brinden apoyo a la producci&oacute;n sustentable fundada en la agricultura familiar y campesina.</p>
</li>
<li>
<p>Es preciso tomar medidas que fomenten y protejan la soberan&iacute;a alimentaria de los pueblos (el derecho de los pueblos y las comunidades a definir sus propias pol&iacute;ticas alimentarias y agr&iacute;colas, as&iacute; como el derecho a producir sus alimentos b&aacute;sicos de forma tal que se respete la diversidad cultural y productiva y se apoye la producci&oacute;n campesina y la agricultura familiar), la inocuidad de los alimentos y la seguridad alimentaria (tanto de los consumidores como de los productores).&nbsp;</p>
</li>
<li>
<p>Las medidas que s&oacute;lo competen a la producci&oacute;n para el consumo nacional y que no contribuyen a incrementar las exportaciones a mercados internacionales deben quedar eximidas de cualquier acuerdo internacional de comercio. Hay que impedir que el sistema de comercio socave el sustento de los campesinos, agricultores familiares, trabajadores agr&iacute;colas, pescadores artesanales y pueblos ind&iacute;genas.</p>
</li>
<li>
<p>Consideramos que el ejercicio de la soberan&iacute;a y seguridad alimentaria y el desarrollo de una agricultura sustentable de base familiar y campesina, le exige a los gobiernos reconocer la imperfecci&oacute;n y fallas de los principios de libre comercio que fundamentan tanto la teor&iacute;a de ventajas comparativas percibidas, como el desarrollo de la agricultura orientada a la exportaci&oacute;n y las pol&iacute;ticas de &ldquo;ajuste estructural&rdquo;; y que sustituyan esas pol&iacute;ticas por otras que le den prioridad y protejan a la producci&oacute;n local, de subsistencia y sustentable, utilizando a tal efecto medidas de control a las importaciones y reglas que garanticen m&eacute;todos de producci&oacute;n sustentable m&aacute;s equitativos.</p>
</li>
<li>
<p>Para garantizar el logro de estos objetivos se requerir&aacute;n diversos acuerdos, probablemente entre ellos una convenci&oacute;n sobre soberan&iacute;a alimentaria y agricultura sustentable, y una declaraci&oacute;n sobre los derechos de los agricultores campesinos y familiares. Con su enfoque actual de liberalizaci&oacute;n del comercio a cualquier costo, ni la OMC ni ning&uacute;n otro &ldquo;tratado de libre comercio&rdquo; son en &uacute;ltima instancia el lugar adecuado para tales reglas, raz&oacute;n por la cual se debe fortalecer otros espacios alternativos para discutirlas.</p>
</li>
</ul>
<p><strong>Frenar la globalizaci&oacute;n orientada por las transnacionales y promover la justicia en el comercio</strong><br /> <br /> Las reglas de comercio de la OMC, as&iacute; como las que emanan de muchos otros acuerdos comerciales regionales vigentes o actualmente en negociaci&oacute;n, promueven el poder corporativo de las grandes empresas en la econom&iacute;a mundial proporcion&aacute;ndoles nuevos derechos de protecci&oacute;n a las inversiones, de propiedad intelectual y otros. Al mismo tiempo, esas reglas perpet&uacute;an las pol&iacute;ticas neoliberales de privatizaci&oacute;n y desregulaci&oacute;n torn&aacute;ndolas irreversibles. Todo esto est&aacute; disfrazado de &ldquo;libre comercio&rdquo;. Este desequilibrio de poder sirve y promueve los intereses econ&oacute;micos mezquinos de algunos pocos gigantes de la econom&iacute;a mundial, a menudo con efectos devastadores para las econom&iacute;as locales y nacionales, particularmente en los pa&iacute;ses en desarrollo.</p>
<p>Este poder empresarial corporativo se est&aacute; fortaleciendo a trav&eacute;s de tratados y acuerdos regionales y bilaterales de comercio e inversiones, cuyas reglas poderosas promueven derechos corporativos para las empresas y constituyen una seria amenaza a la autoridad gubernamental democr&aacute;tica nacional. De conformidad con algunos acuerdos, de hecho, las empresas extranjeras pueden ahora demandar a los gobiernos nacionales por &ldquo;lucro cesante&rdquo; si cualquier ley o reglamentaci&oacute;n del pa&iacute;s reduce sus ganancias actuales o futuras. Los derechos ambientales, laborales y sociales quedan todos subordinados al derecho de las empresas a lucrar. Es imprescindible revertir esta tendencia.</p>
<p>Habiendo frustrado con &eacute;xito el Acuerdo Multilateral de Inversiones (AMI) que hubiera consagrado tales derechos empresariales corporativos, reclamamos que se le ponga fin a la artima&ntilde;a empresarial de fomento a la expansi&oacute;n r&aacute;pida y aventurada de acuerdos regionales y bilaterales de comercio e inversiones como estrategia para apuntalar a la OMC desfalleciente. Asimismo exigimos el cese de cualesquier reglas de comercio que garanticen el derecho de&nbsp; las empresas a lucrar sometiendo a las pol&iacute;ticas regulatorias nacionales a demandas y reclamos de indemnizaci&oacute;n pagaderos con fondos p&uacute;blicos.</p>
<p>Para empezar a movernos hacia un sistema justo de comercio, exhortamos a los gobiernos a negociar un acuerdo vinculante que garantice que las empresas rindan cuenta democr&aacute;ticamente de sus actos y sus impactos sociales, econ&oacute;micos y ambientales, incluso del papel que algunas juegan en apoyo a reg&iacute;menes represivos y el comercio de armas. Este acuerdo debe negociarse a trav&eacute;s de la ONU&nbsp; y otros organismos especializados, con participaci&oacute;n plena de la sociedad civil.</p>
<p>De otra parte, convocamos a las organizaciones y movimientos de la sociedad civil a emprender un di&aacute;logo mundial de la sociedad civil tendiente a desarrollar un sistema de comercio alternativo, justo y sustentable en sustituci&oacute;n del modelo neoliberal &ndash;un sistema que promueva genuinamente un desarrollo sustentable favorable a los pueblos y fundado en sus derechos b&aacute;sicos, y que ponga en primer lugar a las comunidades.</p>
<p>Estamos abocados a la construcci&oacute;n de un sistema de comercio sometido al control democr&aacute;tico, ecol&oacute;gicamente sustentable y socialmente justo. Por lo tanto, como primer paso, exigimos que nuestros gobiernos implementen los cambios enumerados en este documento con vistas a restringir y revertir el poder y la autoridad de la OMC y reorientar el comercio para crear un sistema justo. Nos comprometemos a movilizar a la poblaci&oacute;n de nuestros pa&iacute;ses, en las distintas regiones y en todo el mundo para luchar por estas demandas y combatir las pol&iacute;ticas injustas de la OMC y el sistema general de comercio multilateral.</p>
<p>Las opciones que tenemos son tajantes: o aceptamos el orden mundial imperante centrado en las empresas e hipotecamos el bienestar de las generaciones venideras y el futuro mismo del planeta, o asumimos el dif&iacute;cil desaf&iacute;o de encaminarnos hacia un sistema nuevo centrado en las necesidades de los pueblos, las comunidades y el medioambiente.</p>

        </div> <!-- /#content-area -->
      </div> <!-- /#content -->
    </div> <!-- /#main -->
<?php
include 'include/foot_etc.php'
?>
