#!/bin/bash
for i in index about members contact search news key-positions no-new-round WTO \
	 statement-political-unity declaration-d-unite \
	 documento-di-unita declaracion-unidad-politica join ; do
  php special-page/$i.php > $i.html
done
for i in es fr; do
  php language-page/$i.php > $i.html
done
for i in fish digital UNCTAD WTO-process TRIPS agriculture investment services SDT goods \
	 trade-facilitation ; do
  php theme-page/$i.php > $i.html
done
for i in MC3 MC5 MC11 MC12; do
  php WTO-MC-page/$i.php > $i.html
done
for i in shrink-or-sink 2019_WTO_PF_95 2019_WTO_PF_111 2019_WTO_PF_119 \
	 2019-12-09 digital-trade-rules digital-trade-rules_ES digital-trade-rules_2020 surrendering \
	 Stiglitz 2021-03-17_TWN_Fisheries 2021-04-06_CSO-letter_UNCTAD \
	 2020-04-30_letter_Focus_saving_lives 2020-04-30_carta_Salvar_vidas 2020-04-30_lettre_Sauvetage_de_vies \
	 2020_sovereignty_and_development \
         2021-04-14_PVA-letter \
	 2021_US_Congress_letter \
	 2021_transform_WTO 2021_transform_WTO_ES 2021_transform_WTO_FR \
	 2012_OWINFS_UNCTAD13 2012_OWINFS_UNCTAD13_ES 2012_OWINFS_UNCTAD13_FR \
	 2012_OWINFS_UNCTAD13_PT 2016_speech_UNCTAD14 \
	 2021_MEPs_LDC_extension 2021_CSOs_LDC_extension 2021-06-10_Leterme \
	 2021_SOL_China+India 2021_SOL_China+India_FR \
	 2021_CSO_summary_UNCTAD_mandate 2021_L_UNCTAD_mandate \
	 R_WTO-Turnaround 2021_WTO-Turnaround 2021_WTO-Turnaround_ES 2021_WTO-Turnaround_FR \
	 ; do
  php contentitem-page/$i.php > $i.html
done
