#!/usr/bin/php
<?php
include 'include/solr_add_document.php';

solr_add_htmlfile('', 'Prof. Stiglitz on digital trade', '(3 min video)',
                  'Stiglitz', '2019-04-12', 'en', "Stiglitz.html");

solr_add_htmlfile('', 'About OWINFS: Our World Is Not For Sale', '',
                  'about', '9998', 'en', "about.html");
?>
